"""
This is the main entry point of the application.

Import the bare minimum needed and add any initialization code here.
opencv_createsamples -info amostras.lst -num 1200 -w 24 -h 24 -vec positives.vec
opencv_traincascade -data classifier -vec positives.vec -bg bg.txt -numPos 200 -numNeg 400 -numStages 15 -w 50 -h 50
opencv_traincascade -data classifier -vec positives.vec -bg bg.txt -numPos 1200 -numNeg 600 -numStages 10 -w 24 -h 24 -maxFalseAlarmRate 0.2
opencv_traincascade -data classifier -vec positives.vec -bg bg.txt -numPos 1500 -numNeg 1000 -numStages 10 -w 24 -h 24 -maxFalseAlarmRate 0.2
"""
from src.app.FrontEnd import TelaConfig
def main():
    tela = TelaConfig()
    tela.mainloop()
    
    return 0


if __name__ == "__main__":
    
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
    SystemExit(main())

